version: 2.1

commands: # a reusable command with parameters
  benchmark:
    parameters:
      backend:
        type: string
      quantize:
        type: string
    steps:
      - checkout
      - run:
          command: >
            apt-get update &&
            apt-get -y install curl &&
            curl -o mobilenetv2-1.0.onnx
            https://s3.amazonaws.com/onnx-model-zoo/mobilenet/mobilenetv2-1.0/mobilenetv2-1.0.onnx
          name: Download model
      - run:
          command: >
            python3 ./bench mobilenetv2-1.0.onnx
            --backend <<parameters.backend>>
            --repeat 10
            --number 1
            --warmup 1
            --backend-meta onnx2pytorch
            --device cpu
            --quantize <<parameters.quantize>>
            --output-path results/mobilenet.json
          name: Benchmark pytorch backend
          no_output_timeout: 5m
      - run: test results/mobilenet.json

jobs:
  test-pytorch:
    docker:
      - image: toriml/pytorch:latest
    parameters:
      quantize:
        default: "0"
        type: string
    steps:
      - benchmark:
          backend: "pytorch"
          quantize: <<parameters.quantize>>

workflows:
  main:
    jobs:
      - test-pytorch:
          matrix:
            parameters:
              quantize: ["0", "1"]

