FROM mcr.microsoft.com/azureml/onnxruntime:latest-tensorrt
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    protobuf-compiler \
    libprotobuf-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --no-cache onnx