FROM mcr.microsoft.com/azureml/onnxruntime:latest
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    protobuf-compiler \
    libprotobuf-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache onnx